app/models/opportunity_query.rb
…e_provider.name when sorting after searching in admin/opps
=> [3881] (fix) service provider eager join with opportunities to access service_provider.name when sorting after searching in admin/opps

app/controllers/admin/opportunities_controller.rb, app/controllers/users/omniauth_callbacks_controller.rb, app/policies/editor_policy.rb, app/policies/enquiry_policy.rb, app/policies/opportunity_policy.rb, app/views/admin/opportunities/_form.html.haml, app/views/admin/opportunities/index.html.haml, spec/features/admin_can_filter_opportunities_spec.rb, spec/features/admin_trashes_an_opportunity_spec.rb, spec/features/reviewers_can_create_drafts_spec.rb, spec/features/users_can_sign_in_spec.rb
this is a combination of the draft state and reviewer user type. Rebased from develop, provides both functionality.
=> [742][743] draft state for uploaders, private opps space. reviewer user type. reviewers can do anything an uploader can.

README.md, app/controllers/admin/opportunities_controller.rb, app/controllers/admin/opportunity_status_controller.rb, app/models/editor.rb, app/policies/application_policy.rb, app/policies/editor_policy.rb, app/policies/enquiry_policy.rb, app/policies/opportunity_policy.rb, app/views/admin/registrations/new.html.haml, spec/factories/editors.rb, spec/features/admin_can_filter_opportunities_spec.rb, spec/features/reviewers_can_create_drafts_spec.rb, spec/features/reviewers_can_manage_opportunities.rb, spec/features/reviewers_can_view_enquiries.rb
renaming reviewer to previewer as suggested for clarity.
=> (fix) reviewer->previewer

app/controllers/admin/registrations_controller.rb, app/policies/editor_policy.rb, app/views/admin/editors/show.html.haml, config/locales/devise.en.yml, config/routes.rb, spec/features/admin_manage_editors_spec.rb
A new button reactivate editor in the editor show page can reactivate a deactivated editor.
=> [814] Admin can reactivate a deactivated editor

app/controllers/users/enquiries_controller.rb, app/views/enquiries/new.html.haml, app/views/users/enquiries/includes/outcome/_not_right.html.haml, app/views/users/enquiries/includes/snippets/_trade_profile.html.haml, spec/features/users_can_apply_for_opportunities_spec.rb, spec/features/users_can_view_their_enquiries_spec.rb
https://trello.com/c/ZEtARHkb/1007-1-content-tweaks
=> (fix) removing colon

app/views/admin/enquiries/help.html.haml
The text on trello card was wrong, soz.
=> (feature) yes, changing text again

app/assets/stylesheets/application.scss, app/assets/stylesheets/styleguide_export/_colours.scss, app/assets/stylesheets/styleguide_export/_compromise.scss, app/assets/stylesheets/styleguide_export/_config.scss, app/assets/stylesheets/styleguide_export/_layout.scss, app/assets/stylesheets/styleguide_export/_mixins.scss, app/assets/stylesheets/styleguide_export/_typography.scss, app/assets/stylesheets/styleguide_export/_vars.scss, app/assets/stylesheets/styleguide_export/components/_breadcrumbs.scss, app/controllers/opportunities_controller.rb, app/presenters/page_presenter.rb, app/views/opportunities/show.html.haml, app/views/partials/_breadcrumbs.html.haml
=> Add breadcrumbs to view Opportunity page

app/assets/javascripts/poc/dit.class.simple_text_display_restrictor.js, app/assets/javascripts/poc/layouts/opportunity.js, app/assets/stylesheets/poc/_content.scss, app/assets/stylesheets/poc/_general.scss, app/assets/stylesheets/poc/_mixins.scss, app/assets/stylesheets/poc/components/_breadcrumbs.scss, app/assets/stylesheets/poc/effects/_simple_text_display_restrictor.scss, app/assets/stylesheets/poc/layouts/opportunity.scss, app/controllers/poc/opportunities_controller.rb, app/presenters/poc/opportunity_presenter.rb, app/presenters/poc/page_presenter.rb, app/views/poc/components/_breadcrumbs.html.haml, app/views/poc/opportunities/_opportunity_search_results.html.haml, app/views/poc/opportunities/show.html.haml, config/initializers/assets.rb, config/routes.rb
=> Feature zeus/1321 format oo opps descriptions

app/views/admin/help/how_to_assess_a_company.html.erb
=> Update Admin Help content

app/presenters/poc/opportunity_presenter.rb, app/views/poc/opportunities/show.html.haml
=> Feature zeus/1321 format oo opps direct link

app/controllers/poc/opportunities_controller.rb, app/presenters/poc/opportunities_search_results_presenter.rb, app/views/poc/opportunities/_opportunity_search_results.html.haml, app/views/poc/opportunities/index.html.haml, app/views/poc/opportunities/results.html.haml
Add Country to Search Result title and refactored to (hopefully) help reduce code confusion.
=> Add Country to search result title (with a little refactor)

app/views/enquiry_mailer/send_enquiry.html.haml
=> Fix the email greeting

app/assets/stylesheets/poc/_general.scss, app/assets/stylesheets/poc/layouts/opportunity.scss, app/views/poc/components/_feedback.html.haml, app/views/poc/opportunities/show.html.haml
=> Feature zeus/XOT-105 report opportunity button

app/presenters/poc/opportunity_presenter.rb, app/views/poc/opportunities/show.html.haml
Added ExOpps opportunity equivalent to "more information text"
Plus two fixes
Plus two nonsense (whitespace change) commits trying to get around confusing git "No changes - did you forget to use 'git add'?" rebase messages.
=> Feature zeus/XOT-102 more information text

app/views/enquiry_feedback_mailer/request_feedback.html.haml, app/views/layouts/eig-email.html.erb, app/views/opportunity_mailer/send_opportunity.html.haml, app/views/opportunity_mailer/send_opportunity.text.erb, app/views/poc/includes/_footer_domestic.html.erb
(includes fixes for discovered URL errors in send_opportunity text email)
=> Fix the privacy statement URL

app/views/admin/includes/_flash_announcement.html.haml
(also disabled the font:bold due to large amount of text looking at bit wrong - will see if anyone notices or complains, and reverse if required)
=> Add .gsi and ukti.gsi email addresses change announcement

Gemfile, Gemfile.lock, app/views/includes/_transformation_styles.html.haml, app/views/layouts/application.html.haml, app/views/layouts/enquiries.html.erb, app/views/layouts/form.html.erb, app/views/layouts/landing.html.erb, app/views/layouts/notification.html.erb, app/views/layouts/opportunity.html.erb, app/views/layouts/results.html.erb, config/initializers/assets.rb
This also adds the new performance dashboard link in the footer
https://uktrade.atlassian.net/browse/CMS-181
=> Add assets from header/footer gem

app/presenters/opportunity_presenter.rb, app/presenters/opportunity_search_results_presenter.rb, app/views/email_notifications/show.html.haml, app/views/opportunities/_list.html.haml, app/views/opportunities/index.html.haml, app/views/opportunities/results.html.haml, app/views/opportunity_mailer/send_opportunity.html.haml
(includes a little refactoring of related area in OpportunityPresenter and OpportunitySearchResultsPresenter)
=> Fix OpenOpp title output in email

app/assets/stylesheets/transformation/components/_search_results_filters.scss, app/presenters/opportunity_search_results_presenter.rb, spec/presenters/opportunity_search_results_presenter_spec.rb
(added a test for extra code and had to remove old, unused test for things to pass)
=> Fix duplicated country filter and lack of space between output

app/assets/stylesheets/transformation/components/_opportunity_list.scss
Fixes wrapping for long Opportunity titles in a list (home page 'Latest Opportunities' and search results.
=> Fix Opportunity titles in list

app/services/enquiry_feedback_survey_sender.rb, spec/services/enquiry_feedback_survey_sender_spec.rb
instead of 3 months after opp expiry date
=> (fix) now sending impact email 3 months after enquiry

app/content/enquiry_feedback.yml, app/views/layouts/general.html.erb
Fixing an earlier commit which missed new files.
=> Add missing files that should have been added to earlier commit

app/content/enquiry_feedback.yml
Should now read 'Feedback' only.
=> Fix typo and change to requested single word

spec/presenters/opportunity_search_results_presenter_spec.rb
FE changes to go with search results > max content changes.
=> Update tests for change to found_message

app/content/opportunities/results.yml, app/presenters/opportunity_search_results_presenter.rb, spec/presenters/opportunity_search_results_presenter_spec.rb
Not sure how previous work didn't make PR#443 or was lost. 
This is trying again.
=> Add previously lost work for updating max results exceeded message

app/views/opportunity_mailer/send_opportunity.html.haml, app/views/opportunity_mailer/send_opportunity.text.erb, app/workers/retrieve_volume_opps.rb
Add the word 'new' to phrase 'you have 3 opportunities' line in opportunities digest email
=> Add the word 'new' in opportunities digest email

app/helpers/application_helper.rb, app/models/opportunity.rb, app/services/create_opportunity.rb, app/services/opportunity_quality_retriever.rb, app/services/volume_opps_retriever.rb, app/validators/opps_quality_validator.rb, lib/opps_quality_connector.rb, spec/features/admin_can_reply_to_enquiries_spec.rb, spec/features/editors_can_manage_opportunities_spec.rb, spec/models/opportunity_spec.rb, spec/services/opportunity_quality_retriever_spec.rb, spec/validators/opps_quality_validator_spec.rb
and refactor Qaulity Retriever objects and specs
=> Fix multiple failing tests and refactor Quality Retriever objects 

app/helpers/application_helper.rb, app/mailers/enquiry_mailer.rb, app/models/opportunity.rb, app/services/create_opportunity.rb, app/services/opportunity_quality_retriever.rb, app/services/volume_opps_retriever.rb, app/validators/opps_quality_validator.rb, app/workers/retrieve_volume_opps.rb, db/migrate/20190114110712_set_enqiry_feedback_initial_response_default_to_null.rb, db/migrate/20190114111951_set_enqiry_feedback_initial_response_default_to_null2.rb, lib/opps_quality_connector.rb, spec/features/admin_can_reply_to_enquiries_spec.rb, spec/features/editors_can_manage_opportunities_spec.rb, spec/models/opportunity_spec.rb, spec/services/opportunity_quality_retriever_spec.rb, spec/validators/opps_quality_validator_spec.rb
Fix enquiry_mailer typo / bug
Opportunities sanitise whitespace in description correctly
RetrieveVolumeOpps retries 4 times
Several tests are more reliable
=> Minor fixes

app/assets/stylesheets/transformation/pages/results.scss
Previous fix didn't quite get it right. Hopefully this will.
=> Fix incorrect scrollbar position

config/initializers/elastic_search.rb
**NOTE This will require new Env Variables on staging and production.**
=> updated ElasticSearch to connect to new London service

Gemfile, Gemfile.lock, app/assets/javascripts/transformation/dit.page.all.js, app/assets/stylesheets/transformation/main.scss, app/views/includes/_transformation_styles.html.haml, app/views/layouts/application.html.haml, config/initializers/assets.rb
Note: `HEADER_SEARCH_ON` and `NEWS_SECTION_ON` env vars will need to be set in order to show the search box and the news link respectively. They are off by default
=> Use new header

Gemfile, Gemfile.lock, app/assets/javascripts/transformation/dit.page.all.js, app/assets/stylesheets/transformation/main.scss, app/views/includes/_transformation_styles.html.haml, app/views/layouts/application.html.haml, config/initializers/assets.rb
Reverts uktrade/export-opportunities#501
=> Revert "Use new header"

app/assets/javascripts/transformation/dit.class.cpv_code_lookup.js
Also adds the CPV code to the dropdown to show potential duplicated entries are actually different.
=> Fix confusing text by cleaning and trying to deduplicate entries

app/assets/javascripts/transformation/dit.class.cpv_code_lookup.js, app/assets/stylesheets/transformation/components/_cpv_code_lookup.scss
@WillTaylor22 
~Raising PR to view on CD but don't merge as expect will need further work first.~
Please ignore the above comment as we now want to view it on Staging. Thanks.
=> Add parent description (when available) to CPV options

lib/omniauth/strategies/exporting_is_great.rb
* update manifest
* revert manifest to normal
* fix token url
=> Chore/openauth hotfix (#551)

app/controllers/application_controller.rb, app/models/enquiry.rb, spec/controllers/application_controller_spec.rb, spec/controllers/bulk_subscriptions_controller_spec.rb, spec/controllers/enquiries_controller_spec.rb, spec/controllers/pending_subscriptions_controller_spec.rb, spec/controllers/subscriptions_controller_spec.rb, spec/controllers/users/dashboard_controller_spec.rb, spec/controllers/users/enquiries_controller_spec.rb, spec/features/subscribers_can_unsubscribe_spec.rb, spec/features/users_can_apply_for_opportunities_spec.rb, spec/features/users_can_download_documents_spec.rb, spec/features/users_can_manage_their_subscriptions_spec.rb, spec/features/users_can_opt_out_of_emails_spec.rb, spec/features/users_can_sign_in_spec.rb, spec/features/users_can_subscribe_to_alerts_spec.rb, spec/features/users_can_view_their_enquiries_spec.rb, spec/features/visiting_the_site_on_different_domains_spec.rb, spec/models/enquiry_spec.rb, spec/spec_helper.rb
- Hotfix for Enquiry Form issue
- Users are signed out when accessing SSO-only pages
=> Release - 1 Nov 2019

app/controllers/application_controller.rb, spec/controllers/application_controller_spec.rb
Bugfix causing crash for users who have not gone through new registration journey when applying to opportunities
=> Release 4 November

app/controllers/application_controller.rb, spec/controllers/application_controller_spec.rb
* sign in users if they are signed in on SSO but not on ExOps
=> Release 7 November

app/services/subscription_finder.rb, app/services/subscription_search_builder.rb, spec/services/subscription_finder_spec.rb, spec/services/subscription_search_builder_spec.rb
Update subscription queries to comply with Elasticsearch 7.x API
=> Release 18/11

config/initializers/elastic_search.rb
Add missing requirements following previous change in #949
=> fix: add requires for elastic search

app/views/shared/_migration_banner.erb
=> Change downtime banner date

spec/controllers/api/activity_stream_spec.rb
Ran `rubocop -A` on `spec/controllers/api/activity_stream_spec.rb` to clean up stylings
=> Run rubocop -A

app/assets/stylesheets/export-components/main.scss, app/views/layouts/application.html.haml, app/views/layouts/landing.html.erb, app/views/shared/_migration_banner.erb, config/initializers/assets.rb
=> Add maintance banner and content

app/views/enquiries/new.html.haml
Ticket: https://uktrade.atlassian.net/browse/GRTLV-747
Mural: https://app.mural.co/t/departmentforbusinessandtrad1574/m/departmentforbusinessandtrad1574/1730221317647/d9bb372ba2ef91924a19b35f3e66203eb1acc873
=> Add new consent wording to expressing an interest

app/helpers/domain_helper.rb, spec/helpers/domain_helper_spec.rb
We need to update the `HOTFIX_DOMAIN` variable to match the `DOMAIN` env var to ensure the correct url is used
=> Update HOTFIX_DOMAIN variable
