app/assets/stylesheets/admin/_admin.scss, app/controllers/admin/opportunities_controller.rb, app/controllers/admin/opportunity_status_controller.rb, app/models/opportunity.rb, app/policies/opportunity_policy.rb, app/services/create_opportunity.rb, app/services/update_opportunity_status.rb, app/views/admin/opportunities/_form.html.haml, app/views/admin/opportunities/show.html.haml, production_deployment.sh~, spec/factories/opportunities.rb, spec/features/admin_trashes_an_opportunity_spec.rb, spec/features/administering_opportunities_spec.rb, spec/features/uploaders_can_create_drafts_spec.rb, spec/features/viewing_opportunities_spec.rb, spec/services/update_opportunity_status_spec.rb
Draft state initial functionality.
- On creating a new opp a user can Create(set to pending state) or Save to Draft(state=draft)
- An uploader can move an opp from the show view to these states trash<->draft -> pending . Once it's pending state, it's out of her control and to the editor's/admin's control
- Drafts are private to uploaders
- Admins can view and modify drafts
=> [742] add draft state in admin centre

app/assets/javascripts/enquiries_form.js, app/views/enquiries/new.html.haml, spec/features/users_can_apply_for_opportunities_spec.rb
Note: Have specified 1100 character limit on field, and code indicates similar restriction...
`app/models/enquiry.rb:  COMPANY_EXPLANATION_MAXLENGTH = 1100.freeze`
but when submitted with this number, the error message still shows. 
Reducing the character limit to 1098 appears to be the maximum that can be submitted with being served the error.
=> Add indication of character limit

app/assets/javascripts/poc/dit.class.expander.js, app/assets/javascripts/poc/layouts/results.js
On Search Results page, enhanced filters (open and close expanders) will not be accessible via scoped JS. To test, visit...
`http://localhost:3000/poc/opportunities?filterOpen=&industries%5B%5D=aerospace&isSearchAndFilter=true&paged=2&s=food`
...in a browser and use the Inspector Console to run:
`dit.page.results.expanders[0].open()`
You should see the Regions filter now open. Use `.close()` to reverse the action.
dit is an object on the window scope (so, full location is window.dit.page.results...)
=> Add Filter Expanders to dit.page.results

app/controllers/application_controller.rb, spec/features/webops_can_monitor_elastic_search_spec.rb
new /api_check endpoint, will notice a new failed job in sidekiq based on JobQueue name, start failing, continue complaining for a day.
=> (fix) monitoring /api_check endpoint

app/controllers/api/activity_stream_controller.rb, spec/controllers/api/activity_stream_spec.rb
We don't have network-level firewall capabilities, but in PaaS, the
second-to-last element in the X-Forwarded-For header cannot be spoofed.
=> (feat) X-Forwarded-For spoofing mitigation

app/views/opportunities/_search_form.html.haml
This is an attempt to see if removing the 'tick' parameter (originally intended as a Rails fix for older IE browsers), makes any difference in the weird 'clear all filters' issue that affects only IE (the one where a page refresh shows a working page). 
It is a 'have nothing else to offer' attempt to avoid putting in the auto-refresh hack that has been discussed.
=> Fix attempt for weird IE issue

config/puma.rb
None of the code passed to `ActiveSupport.on_load(:rails)` appeared to be
running. Note the examples at https://github.com/puma/puma use
`ActiveSupport.on_load(:active_record)`
=> (refactor) Remove dead code

config/puma.rb
From testing on staging, these (and similar) changes reduced frequency of 502s
and booted workers. It did not completely eliminate them however.
----
On production, there are 900 threads, spread over 4 instances, 8 processes per
instance, 30 threads per process, 8G memory per instance. If each thread used
as much memory as it could, at most 33mb per thread. Some brief heap analysis
locally appeared to show that starting a thread takes ~30mb of memory, so this
appears to be too low.
Also, there are documented 500 max connections to the database being used, so
even if all of these threads could be used at once, many would fail.
There are also (apparently) max of 4 cores on each instance: so in terms of
parallel processing, there can never be more than 4 instructions being executed
in …
=> (feat) Decrease thread and process limits

Procfile
A few bits of subtle behaviour here...
- There was no existing "command" process running, so the CI pipeline did not
instantiate a "command" process. This means the migrations were not
running.
- Without a "web" process specified, the default one in the buildback was
running. In this case, the default one for the Ruby buildpack made
everything work.
- The default memory for a "web" process is also set to 1gb. Without it being
specified in the Procfile, the CI pipeline script does not ensure to scale
it to match the existing "web" process.
=> (fix) Deployments were scaling to 1gb of memory, suspect migrations not running

config/environments/production.rb
I'm suspecting compiling templates is slow, and possibly leaky looking at stack
dumps. Also, there has been IO problems in production, and I've seen checking
file modification times in Sentry errors, so this may go some way in addressing
those.
=> (feat) Cache classes: among other things, it caches compiled templates

app/workers/retrieve_volume_opps.rb
Rather than retrying exactly 3 times every 1 minute, this will retry 4 times over a 5-minute interval.
The reason for this is that our Sidekiq gem intentionally makes it difficult to customise the timing interval. From the documents:
"No More Bike Shedding
Sidekiq's retry mechanism is a set of best practices but many people have suggested various knobs and options to tweak in order to handle their own edge case. This way lies madness. Design your code to work well with Sidekiq's retry mechanism as it exists today or patch the JobRetry class to add your own logic. I'm no longer accepting any functional changes to the retry mechanism unless you make an extremely compelling case for why Sidekiq's thousands of users would want that change."
Therefore the cost associated with building a custom …
=> Retrieving volume opps retries multiple times

config/initializers/elastic_search.rb
b/c Gov PaaS only has ES up to medium size and we need L
=> (fix) rollback elastic_search_url

app/controllers/api/activity_stream_controller.rb
* Bug/fix enquiry response ambiguity error (#726)
* Add index to subscription notifications and improve seeds (#723)
* Fix bug
* Hotfix - remove index adding (#728)
* update migrtions
* remove adding index
* Fix           response.headers['Content-Type'] = 'application/json'
causing errors
=> Bug/hotfix respond to mismatch error 30 june (#735)

app/controllers/application_controller.rb
Remediation for the edge case where a user comes from BAU but is not present in the database. The outcome is a new user is created and signed in providing the presence of a cookie with a valid SSO session key.
=> Create users from a valid SSO session when they don't exist

app/controllers/application_controller.rb, app/controllers/users/omniauth_callbacks_controller.rb
This PR makes a `current_user` also dependant on the presence of a sso session
=> Require auto sign-in to have both app and sso sessions

app/controllers/application_controller.rb
This release removes the requirement of an SSO session to be present in the Admin (editor) section
=> Bypass SSO session requirement for editors (#781)

app/controllers/api/activity_stream_controller.rb, spec/controllers/api/activity_stream_spec.rb
This is to have more data in Data Workspace. This should not result in more opportunities exposed in the Great search, due to https://github.com/uktrade/great-cms/pull/1616
=> feat: include expired opportunities in Activity Stream endpoint

manifest.yml
Enforcing `cflinux3` until the runtime is upgraded to Ruby 3.x
=> KLS-1487 cflinux4 upgrade

app/controllers/api/activity_stream_controller.rb, spec/controllers/api/activity_stream_spec.rb
We can remove the IP checks as HAWK will deal with the authentication. Similarly  to here https://github.com/uktrade/directory-sso/pull/837/files where directory sso relies on just HAWK to authenticate
=> Remove IP check as handled by HAWK

app/controllers/admin/enquiries_controller.rb, app/models/enquiry_csv.rb, app/workers/send_enquiries_report_to_matching_admin_user.rb
The original process was to load all CSV data into memory at once, which would cause the process to be killed due to limited memory.
This PR enables processing data in smaller chunks and uses files for temporary storage, now as a background job.
=> Generate enquiries report as background job

app/controllers/api/activity_stream_controller.rb, spec/controllers/api/activity_stream_spec.rb
Ex-ops HCSAT should have a `feedback_submission_date` which is the `created_at` date in the ex-ops table. The fields should match the fields for domestic Ex-ops.
@divyaparameswaran There will most likely need to be a change in air flow repo to now match against the field renaming :)
=> Update csat created_at to be feedback_submission_date for activity stream

app/presenters/opportunity_presenter.rb
Depending on the env, the markets page has a different URL. So if not great.gov.uk we will go to `/export-from-uk/markets/`
=> Update URL to go to different markets page
